### PR TITLE
Update composer.json to support Symfony 7

### LINKED ISSUE #24: Allow symfony V7.0
Symfony V7 is now released.

### PR DESCRIPTION
**Pull request by Pixelshaped**
Hi! As title says... We need this to be able to use this bundle with Symfony 7, which is available.

Fix #24

### CODE REVIEW

**Comment by Pixelshaped** [comment]
@devnix FYI I've tested the upstream branch in my project and it works perfectly fine with Symfony 7, with no further modifications whatsoever.

**Comment by Pixelshaped** [comment]
I got rid of this package and am using instead instructions found at this link.
https://github.com/doctrine/DoctrineMigrationsBundle/issues/38#issuecomment-1091154072

Might still be nice to merge for others, there are a bunch of users of this package, and this PR is really inoffensive.

**Comment by kaiwa** [comment]
Ping @devnix

**Comment by devnix** [comment]
I'm no longer giving updates to this project. It has some quirks that I never got the time to fix, and there are no tests guaranteeing compatibility with all "supported" Symfony versions or that something is broken.

I strongly suggest several alternatives:
- Try to achieve the same functionality with a makefile, [here is a practical example](https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle/discussions/21)
- **Put your energies into pushing this functionality into the core project, rather than into an unmaintained package**
- Fork this repository and maintain your package
- Also, ask yourself: do you _really_ need different databases? Like _really really_?

I'm archiving the project here in GitHub and abandoning it on Packagist.

**Pull request closed without merging**
