### PR TITLE
removed deprecations warnings on sf6.1

### PR DESCRIPTION
**Pull request by maikelohcfg**
Removed deprecations warnings on symfony 6.1

### CODE REVIEW

**Comment by devnix** [comment]
I'm unsure about this PR, as I would like to keep it compatible with previous versions for now

**Comment by ninsuo** [comment]
> I'm unsure about this PR, as I would like to keep it compatible with previous versions for now

`setName()` is supported since the beginning, thus BC is kept

**Comment by mdeherder** [comment]
Can we consider a merge of this PR ?

**Comment by devnix** [comment]
Superseded by #14

**Pull request closed without merging**
